apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-qa
  namespace: lasample
  labels:
    app: nginx-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-qa
  template:
    metadata:
      labels:
        app: nginx-qa
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
